version: 2

updates:
  # ---- Cargo (Rust) ----
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      cargo-all:
        patterns: ["*"]                 # include all crates
        update-types: ["major","minor","patch"]  # = all updates

  - package-ecosystem: "cargo"
    directory: "/crates/tod-e2e"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      cargo-all:
        patterns: ["*"]                 # include all crates
        update-types: ["major","minor","patch"]  # = all updates

  # ---- GitHub Actions ----
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      gha-all:
        patterns: ["*"]                 # include all actions
        update-types: ["major","minor","patch"]  # = all updates
