version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - alanvardy
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - stacksjb
    commit-message:
      prefix: "chore"
      include: "scope"
