name: Dependabot Full CI

permissions:
  contents: read

on:
  # Triggered for PRs created or updated by Dependabot or manually.
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]')
    uses: ./.github/workflows/_reusable-test.yml
    with:
      os_matrix: '["ubuntu-latest","ubuntu-24.04-arm","macos-latest","windows-latest"]'
      upload_codecov: false
