name: Release Homebrew Formula

on:
  workflow_dispatch:  # Allows manual triggering

  workflow_run:       # Automatically trigger when both jobs succeed
    workflows: ["macOS Build & Release", "Linux Build & Release"]
    types:
      - completed

permissions:
  contents: write  # Need write permission to dispatch event

jobs:
  trigger-homebrew-update:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Dispatch to homebrew-tod
    runs-on: ubuntu-latest

    steps:
      - id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.TODD_APP_ID }}
          private-key: ${{ secrets.TODD_PRIVATE_KEY }}
          owner: tod-org  # Ensure token is scoped to the target org

      - name: Trigger homebrew-tod update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: tod-org/homebrew-tod
          event-type: update-homebrew
